# Generated by Django 4.2.3 on 2023-07-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="Slug"),
        ),
    ]
