# Generated by Django 4.2.3 on 2023-07-18 14:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_page_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
