# Generated by Django 4.2.3 on 2023-07-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_page_content_alter_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="tag",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.tags", verbose_name="Tag"
            ),
        ),
    ]
